service: bitmovin-sprite-lambda

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  entry:
    handler: src/handler.entry
    description: Description of the function
  test:
    handler: src/handler.test

plugins:
   - serverless-offline
   - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    babelOptions:
      presets: ["es2015"]
